version: '3'
services:
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    volumes:
      - redis:/data
    networks:
      - internal

  mysql:
    image: mysql:8.0
    restart: always
    command:
      - --default-authentication-plugin=mysql_native_password
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_DATABASE: ${DB_DATABASE}
    networks:
      - internal

  nginx:
    ports:
      - '8080:80'
    volumes:
      - './docker/nginx.conf:/etc/nginx/conf.d/default.conf'
      - ./app:/app
      - './.env:/app/.env'
      - './docker/supervisord.conf:/etc/supervisord.conf'
    environment:
      - 'VIRTUAL_HOST=${VIRTUAL_HOST}'
      - 'LETSENCRYPT_HOST=${VIRTUAL_HOST}'
    image: nginx
    networks:
      - internal

  app:
    volumes:
      - ./app:/app
      - './.env:/app/.env'
      - './docker/supervisord.conf:/etc/supervisord.conf'
    build: ./docker
    networks:
      - internal

#Docker Networks
networks:
  internal: #Volumes
volumes:
  db:
  redis:

